services:
  mongodb:
    image: mongo
    container_name: tiktok_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: tiktok_demo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local